spring:

  application:
    name: payflow

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/payflow}
    username: ${SPRING_DATASOURCE_USERNAME:payflow}
    password: ${SPRING_DATASOURCE_PASSWORD:payflow}

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: validate

    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: payflow-audit-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.obvly.payflow.payment.event

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

payflow:
  audit:
    consumer:
      enabled: ${PAYFLOW_AUDIT_CONSUMER_ENABLED:true}
